sonar.projectKey=order-inventory-management
sonar.projectName=Order Inventory Management
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml