spring.application.name=order-inventory-management
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/sprint
spring.datasource.username=root
spring.datasource.password=Narayani@103
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true